---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/about/_index.md
  label: Info Page
- type: document
  path: content/connect/_index.md
  label: Connect
- type: directory
  path: content/blog-posts
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - project
  - blog
- type: document
  path: projects/_index.md
  label: Work
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - about-page
  - project
- type: heading
  label: Config
- type: document
  path: themes/tale-theme/data/Settings.toml
  label: Design Settings
- type: document
  path: config.toml
  label: Site Config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.6
