---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: text
  name: subtitle
  label: Subtitle
- type: datetime
  name: date
  label: date
- type: text
  name: type
  label: type
- type: text
  name: author
  label: author
- type: text
  name: hero
  label: hero
- type: datetime
  name: default
  label: default
- type: list
  name: categories
  label: Categories
  description: Areas of work
- type: text
  name: homepageSummary
  label: Homepage Summary
- type: text
  name: projectPageSummary
  label: Project Page Summary
- type: text
  name: cardImageSlug
  label: Name of Homepage Image
- name: frontPageOrder
  type: number
  label: Front Page Order
  description: This is the order of the pages on the homepage.  Sorted small to big.
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: workOrder
  type: number
  label: Work Order
  description: 'The listing order for the work page. '
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
pages:
- content/projects/billie-s.md
- content/projects/hamilton-goods.md
- content/projects/hamilton-the-musical.md
- content/projects/mason-plumlee.md
- content/projects/mattei-s-tavern.md
- content/projects/migo.md
- content/projects/nectarine-grove.md
- content/projects/nexto.md
- content/projects/nyu-tisch.md
- content/projects/offshore.md
- content/projects/pace.md
- content/projects/parish-food-goods.md
- content/projects/parish-website.md
- content/projects/postino.md
- content/projects/tap.md
- content/projects/the-crack-shack.md
- content/projects/the-lucky-well.md
- content/projects/the-painted-duck.md
- content/projects/the-painted-pin.md
- content/projects/three-sixty.md
- content/projects/trail-rail.md
- content/projects/waterkeeper-20th.md
- content/projects/waterkeeper-magazine.md
