---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: Title
- type: text
  name: subtitle
  label: Subtitle
- type: datetime
  name: date
  label: date
- type: text
  name: type
  label: type
- type: text
  name: author
  label: author
- type: text
  name: hero
  label: hero
- type: datetime
  name: default
  label: default
- type: list
  name: categories
  label: Categories
  description: Areas of work
- type: text
  name: homepageSummary
  label: Homepage Summary
- type: text
  name: projectPageSummary
  label: Project Page Summary
- type: text
  name: cardImageSlug
  label: Name of Homepage Image
